services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    restart: always
    volumes:    
      - ./nginx:/nginx # Keep same as in php container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
        - php
        - db
        
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    restart: always
    volumes:
      - ./nginx:/nginx # Keep same as in nginx container
      - ./php/php.ini:/usr/local/etc/php/php.ini
      
  db: # Database
    image: lscr.io/linuxserver/mariadb:latest
    restart: always
    volumes:
      - ./mariadb:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Amsterdam
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
  phpmyadmin: # Not required - just for convenience.
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1