FROM php:8.1-fpm
###########
# Prereqs #
###########
RUN apt update && apt install -y zip unzip libzip-dev

###########
# Plugins #
###########

# Zip
RUN docker-php-ext-configure zip && docker-php-ext-install zip

# Mysqli
RUN docker-php-ext-configure mysqli && docker-php-ext-install mysqli
