version: '3.0'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    restart: always
    volumes:    
      - /Users/**changeme**/Documents/Development/Web:/var/www
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
        - php
        - db
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    restart: always
    volumes:
      - /Users/**changeme**/Documents/Development/Web:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb:/etc/mysql/conf.d
    env_file:
      - mariadb.env
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
